<?php
    $nav = "<!--nav -->";
    $nav += "<nav class='nav-primary hidden-xs' >";
    $nav += "<ul class='nav bg clearfix' >";
    $nav += "<li class='hidden-nav-xs padder m-t m-b-sm text-xs text-muted' >";
    $nav += "Discover Beats";
    $nav += "</li >";
    $nav += "<li >";
    $nav += "<a href = 'pick-beats.php' >";
    $nav += "<i class='icon-disc icon text-success' ></i >";
    $nav += "<span class='font-bold' > What's new</span>";
    $nav += "</a>";
    $nav += "</li>";
    $nav += "<li class='m-b hidden-nav-xs'></li>";
    $nav += "</ul>";
    $nav += "<ul class='nav bg clearfix'>";
    $nav += "<li class='hidden-nav-xs padder m-t m-b-sm text-xs text-muted'>";
    $nav += "<li >";
    $nav += "<a href = 'top-music.php' >";
    $nav += "<i class='icon-disc icon text-success' ></i >";
    $nav += "<span class='font-bold' > Top Music</span>";
    $nav += "</a>";
    $nav += "</li>";
    $nav += "<li class='m-b hidden-nav-xs'></li>";
    $nav += "</ul>";
    $nav += "<ul class='nav bg clearfix'>";
    $nav += "<li class='hidden-nav-xs padder m-t m-b-sm text-xs text-muted'>";
    $nav += "Recording Studio";
    $nav += "</li>";
    $nav += "<li>";
    $nav += "<a href='#'>";
    $nav += "<i class='icon-microphone icon text-success'></i>";
    $nav += " <span class='font-bold'>Book a Session</span>";
    $nav += "</a>";
    $nav += "</li>";
    $nav += "<li>";
    $nav += "<a href='fullcalendar.php'>";
    $nav += "<i class='icon-calendar icon text-success'></i>";
    $nav += "<span class='font-bold'>My Calendar</span>";
    $nav += "</a>";
    $nav += "</li>";
    $nav += "<li>";
    $nav += "<a href='upload.php'>";
    $nav += "<i class='icon-cloud-upload icon text-success'></i>";
    $nav += "<span class='font-bold'>Upload</span>";
    $nav += "</a>";
    $nav += "</li>";
    $nav += "<li class='m-b hidden-nav-xs'></li>";
    $nav += "</ul>";
    $nav += "</nav>";
    $nav += "<!-- / nav -->";
?>